language: node_js
node_js:
- '8'
before_script:
- npm install --global @dhis2/deploy-build
script:
- npm run lint
- npm run coverage
- npm run build
deploy:
- provider: script
  script: deploy-build
  skip_cleanup: true
  on:
    all_branches: true
- provider: script
  script: publish-build
  skip_cleanup: true
  on:
    tags: true
after_script:
- "./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT"
env:
  global:
    secure: d+6BNgMJeUDcNmUTIpUul9PenY1cwDswQmYVtz4x+6IoS3vOU96y+B3iOb5mPxJGntOVc6gxlCTTqJ+gFvA2CSrFCyIc7vTn+bcTyvi1nNMXnb7a242nFQq2bYystjZNvBmrKH/hWq2qGgBHC5SIrE1pgoetOzMWEfkh2W5tBBUhOS25JBWJZ5X8AzQWl0FjjXnNiRO9yPSVYFYHVT+m/fuJDoQjsK2RmYliuNhX/EmxK7Q8WdteCNlMZAvWqFS2htiBRuwwBRN/eYhvJ++9jeE2BCBgmhkSzqANMdcbPyupKD32WnGlGppO0oy2Ivq+OA/uflKwi4Nzm9mc/EbvgWJ2NGNR/wVkrX/Tf2YLbnTxWts4lQd3qEb4H4IeT/urVvZB+8z9au0AKlMJZpvPwJZLbBorJfmhWZnI2wlfPXU5im7QNqpYb5ydsqs1qHtAriGTkxYU3HHXq4Z67RLZyF832cK4gZXA9uqLxCiPTLvhXwEgDbymgpnX2yT0MaKkL5b2C/mwRbhPLf0SNNabGKFPvkIq7WKvVXfjLuBcxDFkNrSiniJgS9hhsFp/Ox27MB+mxJsvGr1BR3Fu85vdtEU7pWZ3Z49i4nxTtZBYAsSRlckmOwmtYbAzoOw07z7vU7Lpmif1cULyQs3RoWuxwmmFHN2vnT/sM6JhqoZSTEE=
